--
-- Create Sequences
--
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ROLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRIVILEGE_SEQ START WITH 1 INCREMENT BY 1;
--
-- Create Tables
--
CREATE TABLE USERS (
	ID			BIGINT			DEFAULT  USER_SEQ.NEXTVAL		NOT NULL, 
	USERNAME	VARCHAR(255)	NOT NULL,
	PASSWORD	VARCHAR(255)	NOT NULL,
	PRIMARY KEY (ID)
);
--
CREATE TABLE ROLES (
	ID			BIGINT			DEFAULT  ROLE_SEQ.NEXTVAL		NOT NULL,
	NAME		VARCHAR(255)	NOT NULL,
	PRIMARY KEY (ID)
);
--
CREATE TABLE PRIVILEGES (
	ID			BIGINT			DEFAULT  PRIVILEGE_SEQ.NEXTVAL		NOT NULL,
	NAME		VARCHAR(255)	NOT NULL,
	PRIMARY KEY (ID)
);
--
-- Create Weak Entities
--
CREATE TABLE USERS_ROLES (
	USER_ID 	BIGINT			NOT NULL,
	ROLE_ID 	BIGINT			NOT NULL,
	PRIMARY KEY (USER_ID, ROLE_ID)
);
ALTER TABLE USERS_ROLES ADD CONSTRAINT FK_UR_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID);
ALTER TABLE USERS_ROLES ADD CONSTRAINT FK_UR_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID);
--
CREATE TABLE ROLES_PRIVILEGES (
	ROLE_ID 	BIGINT			NOT NULL,
	PRIVILEGE_ID BIGINT			NOT NULL,
	PRIMARY KEY (ROLE_ID, PRIVILEGE_ID)
);
ALTER TABLE ROLES_PRIVILEGES ADD CONSTRAINT FK_RP_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID);
ALTER TABLE ROLES_PRIVILEGES ADD CONSTRAINT FK_RP_PRIVILEGES FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGES(ID);