CREATE SEQUENCE TASK_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE TASKS (
	ID				BIGINT			DEFAULT  TASK_SEQ.NEXTVAL		NOT NULL,
	TASK			VARCHAR(255)	NOT NULL,
	CREATED_BY		VARCHAR(255)	NOT NULL,
	CREATION_DATE	TIMESTAMP		NOT NULL,
	MODIFIED_DATE	TIMESTAMP				,
	PRIMARY KEY(ID)
);