INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('admin', 'admin');
--
INSERT INTO ROLES (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES (NAME) VALUES ('ROLE_EDITOR');
INSERT INTO ROLES (NAME) VALUES ('ROLE_USER');
--
INSERT INTO PRIVILEGES (NAME) VALUES ('READ_PRIVILEGE');
INSERT INTO PRIVILEGES (NAME) VALUES ('WRITE_PRIVILEGE');
INSERT INTO PRIVILEGES (NAME) VALUES ('DELETE_PRIVILEGE');
--
-- Insert Weak Entities Data
--
INSERT INTO USERS_ROLES VALUES (1, 1);
--
INSERT INTO ROLES_PRIVILEGES VALUES (1, 1);
INSERT INTO ROLES_PRIVILEGES VALUES (1, 2);
INSERT INTO ROLES_PRIVILEGES VALUES (1, 3);
INSERT INTO ROLES_PRIVILEGES VALUES (2, 1);
INSERT INTO ROLES_PRIVILEGES VALUES (2, 2);
INSERT INTO ROLES_PRIVILEGES VALUES (3, 1);